### ISSUE TITLE
Generator uncaught exception

### ISSUE THREAD

**Issue by dylangrafmyre** [adobe-photoshop/generator-core#346]
When photoshop is started by one user on a multi tenancy, environment workstation, the second user running photoshop receives a generator error.

Photoshop error:
```
There is a problem with Generator. Please quit Photoshop and try again. If the problem persists, remove any third-party plug-ins or try to reinstalling Photoshop
```

Here is the generator log from the failing PS runtime:
```
Log file created on Fri Apr 22 2016 07:04:57 GMT+0000 (Coordinated Universal Time)
[debug:core 07:04:57.452 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:103:17] Launching with config:
{}
[debug:core 07:04:57.454 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:105:21] provided PS information:
 version 16.0.0
 pathundefined

[info:core 07:04:57.460 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:205:25] Detected Photoshop version: 16.0.0
[debug:core 07:04:58.508 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1718:21] Loading plugin: generator-assets
[debug:core 07:04:59.326 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1734:21] Plugin loaded: generator-assets
[debug:core 07:04:59.330 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1718:21] Loading plugin: crema
[debug:core 07:05:01.258 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1734:21] Plugin loaded: crema
[debug:core 07:05:01.260 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1718:21] Loading plugin: adobe-preview-generator-plugin
[debug:core 07:05:03.204 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1734:21] Plugin loaded: adobe-preview-generator-plugin
[debug:core 07:05:03.207 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1718:21] Loading plugin: photoshop-processor
[debug:core 07:05:07.224 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:1734:21] Plugin loaded: photoshop-processor
***************** SVG is enabled - OMG!
requesting document info
[warning:core 07:05:08.091 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Generator-builtin\lib\generator.js:122:25] Photoshop error { id: 17, body: 'Error: No image open' }
[warning:generator-assets 07:05:08.095 C:\Program Files\Adobe\Adobe Photoshop CC 2015\Required\Plug-Ins\Generator\assets.generate\lib\documentmanager.js:300:26] Error: No image open
[1;31mUncaught exception on Fri Apr 22 2016 07:05:08 GMT+0000 (Coordinated Universal Time):
Error trace: Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:492:13)


[0m[1;31mError: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:492:13)
[0m[1;31mExiting with code -1: Uncaught exception: listen EADDRINUSE
[0m
```

Removing the third party plugin does not resolve this issue with the generator.

Any suggestions on how to resolve this issue?

Thanks
Dylan

**Comment by mcilroyc** [comment]
@dylangrafmyre to help isolate the issue, can I ask you to please temporarily move the `preview.generate` folder out of this common plugins location: `C:\Program Files\Common Files\Adobe\Plug-Ins\CC\Generator` to see if the issue persists?

**Comment by dylangrafmyre** [comment]
@mcilroyc Yes, removing the `preview.generate` plugin resolved this issue. Thank you!!!

**Comment by jinsonkv** [comment]
Finally found a solution here. You can disable Generator feature on Photohsop CC 2020 to fix this.
[There is a problem with generator – Photoshop CC 2020](https://techiestechguide.com/there-is-a-problem-with-generator-photoshop/)
