### ISSUE TITLE
Cannot set headers after they are sent

### ISSUE THREAD

**Issue by pixels4nickels** [adobe-photoshop/generator-core#391]
Since updating to the latest CEP library I am seeing these errors after sending an event. I would like to get more information but node-inspector will not show me any source files to debug ( I am running node/generator locally)

This error halts generator and causes things to break.
```
Uncaught exception on Fri Jul 21 2017 12:26:23 GMT-0700 (PDT):
Error trace: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/krogers/dev/lsr-viewer-plugin/generator/plugins/lsr-generator/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/Users/krogers/dev/lsr-viewer-plugin/generator/plugins/lsr-generator/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/krogers/dev/lsr-viewer-plugin/generator/plugins/lsr-generator/node_modules/express/lib/response.js:256:15)
    at ServerResponse.send (/Users/krogers/dev/lsr-viewer-plugin/generator/plugins/lsr-generator/node_modules/express/lib/response.js:158:21)
    at plugin.generatePreview.serverInstance.sendEvent.GeneratorStatus.documentId (/Users/krogers/dev/lsr-viewer-plugin/generator/plugins/lsr-generator/server.js:141:15)
    at /Users/krogers/dev/lsr-viewer-plugin/generator/plugins/lsr-generator/plugin.js:66:21
    at /Users/krogers/dev/lsr-viewer-plugin/generator/plugins/lsr-generator/png_generator.js:342:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by pixels4nickels** [comment]
Here is the code causing the error:
`app.post('/generate-preview', function (req, res) {
  console.log('/generate-preview');
  res.contentType = 'application/json';

  getPluginInstance(req.query.document_id, true, function(err, plugin) {
    if (err) {
      if (plugin) {
        removeBusyDocument(plugin.currentDocument);
      }
      res.status(400).send(err.asJSON());
    } else {
      plugin.generatePreview(function(err, data) {
        removeBusyDocument(plugin.currentDocument);

        if (err) {
          res.status(400).send(_.extend(err.asJSON(), documentProperties(plugin.currentDocument)));
        } else {
          res.send(_.extend(data, documentProperties(plugin.currentDocument)));
        }
      }, function(progress){
        serverInstance.sendEvent(new GeneratorStatus('previewProgress', { documentId: plugin.currentDocument.id, progress: progress }));
      });
    }
  });
});`

**Comment by pixels4nickels** [comment]
By the way, the use case when this happens is after the preview generation is complete. It feels like it has to do with the final progress event.

**Comment by pixels4nickels** [comment]
For now I believe this issue lies outside of the scope of the generator-core library. Closing for now.
